/**
 * @file    Transmsion_Laser_IR.h
 * @brief   IR laser transmitter driver via Timer PWM on STM32L433.
 *
 * @details Transmits IR frames at 40 kHz carrier frequency using a timer
 *          in PWM mode (Tx_IR_TIM_HANDLE) and a second timer for microsecond
 *          delays (Tx_IR_DELAY_TIM_HANDLE). Both timers must be initialized
 *          by CubeMX before calling Tx_IR_Init().
 *          CubeMX configuration (this board):
 *          - TIM2 CH3 in PWM Generation mode, Prescaler=79, ARR=24, CCR=12
 *            for 50 % duty at 40 kHz. Output pin: PA2 ("TX_LASER").
 *            ARR is shared with the buzzer (TIM2 CH2) — this driver
 *            re-enforces ARR=24 before every transmission.
 *          - TIM1 as a free-running counter (Internal Clock, no channel/pin),
 *            Prescaler=79, Period=65535, for µs delays.
 *
 * @date    March 12, 2026
 * @author  César Pérez
 * @version 1.0.0
 */

#ifndef TRANSMISION_LASER_IR_H
#define TRANSMISION_LASER_IR_H

#include "stm32l4xx_hal.h"
#include <stdint.h>
#include <stdbool.h>

/* ========================  CONFIGURATION  ================================= */

/* PWM timer for the 40 kHz carrier */

#define Tx_IR_TIM_HANDLE            htim2
#define Tx_IR_TIM_CHANNEL           TIM_CHANNEL_3
#define Tx_IR_TIM_CCR_ACTIVE        12U     /**< CCR for 50 % duty (ARR = 24) */

/* Free-running timer used for microsecond delays */

#define Tx_IR_DELAY_TIM_HANDLE      htim1

/* GPIO pin used as AF output for the IR burst */

#define Tx_IR_GPIO_PORT             GPIOA
#define Tx_IR_GPIO_PIN_NUM          2U      /**< PA2 ("TX_LASER")             */

/* ====================  DEVICE CONSTANTS  ================================== */

/* Protocol timing in microseconds */

#define Tx_IR_MARK_US               400U
#define Tx_IR_SPACE0_US             400U
#define Tx_IR_SPACE1_US             800U
#define Tx_IR_INTER_US              1200U
#define Tx_IR_SYNC_US               1600U

/* Calibration frame code — sent when laser_calibration_mode is true.
 * 0xAA = 10101010, 0x55 = 01010101 (patron facil de leer en osciloscopio). */

#define LASER_CAL_CODE              0xAA55UL

/* Frame size limits */

#define Tx_IR_MAX_DATA_BYTES        8U
#define Tx_IR_FRAME_MAX_BYTES       (Tx_IR_MAX_DATA_BYTES + 1U)  /**< +1 checksum */

/* Antirrebote del gatillo (EXTI), en ms */

#define GATILLO_DEBOUNCE_MS         300U

/* External HAL handles generated by CubeMX */

extern TIM_HandleTypeDef Tx_IR_TIM_HANDLE;
extern TIM_HandleTypeDef Tx_IR_DELAY_TIM_HANDLE;

/* Global game state — declared in main.c, true = calibration mode */

extern bool laser_calibration_mode;

/* true solo durante un Ejercicio real (no Calibrar) despues de que termina
 * la cuenta regresiva -- mientras esta en false, el gatillo no dispara.
 * La pone ExerciseTask (Tareas_Interrupciones.c). */
extern volatile bool ejercicio_disparo_habilitado;

/* Bandera puesta en alto por la ISR del gatillo tras enviar el codigo de
 * calibracion; MenuTask la revisa cada ciclo para imprimir el log fuera
 * de la ISR, y la vuelve a bajar. */

extern volatile bool gatillo_disparo_pendiente_log;

/* Contadores de diagnostico temporal (ver Transmision_Laser_IR.c) */

extern volatile uint32_t gatillo_isr_entradas;
extern volatile uint32_t gatillo_disparos_enviados;

/* ================================  API  =================================== */

/**
 * @brief  Initializes the IR transmitter module.
 * @note   Forces PA2 to GPIO Output Low as the idle state.
 *         Call once in main.c after TIM1 and TIM2 are initialized.
 */
void Tx_IR_Init(void);

/**
 * @brief  Transmits a complete IR frame with an automatically computed XOR checksum.
 * @param  pData  Pointer to the data buffer to transmit.
 * @param  len    Number of data bytes (1 to Tx_IR_MAX_DATA_BYTES).
 * @note   Returns HAL_OK on success, HAL_ERROR if pData is NULL, len is 0,
 *         or len exceeds Tx_IR_MAX_DATA_BYTES.
 */
HAL_StatusTypeDef Tx_IR_SendFrame(const uint8_t *pData, uint8_t len);

/**
 * @brief  Transmits the fixed calibration code LASER_CAL_CODE (0xAA55), no CRC.
 * @note   Call when laser_calibration_mode is true. Blocking (~15-20ms).
 */
void Tx_IR_SendCalibration(void);

#endif /* TRANSMISION_LASER_IR_H */
